---
# Hardware configuration file
# Guition ESP32-P4-jc4880p443 4.3" 480X800
#
# https://github.com/wegi1/ESP32P4-JC4880P443C-I-W/blob/main/5-Schematic/JC4880P443_V1.0.pdf

substitutions:
  # Screen Size (portrait orientation - 4.3" display)
  # Swapped automatically for 90/270 rotation
  screen_height: ${800 if rotation | default("90") not in ["90", "270"] else 480}
  screen_width: ${480 if rotation | default("90") not in ["90", "270"] else 800}

esphome:
  min_version: 2026.4.0
  project:
    name: "Guition.ESP32-P4-jc4880p443"
    version: "1.0"

esp32:
  board: esp32-p4-evboard
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: true

esp_ldo:
  - channel: 3
    voltage: 2.5V

psram:
  speed: 200MHz

preferences:
  flash_write_interval: 5min

http_request:  # Needed by esp32_hosted-update and any JSON stuff
  buffer_size_rx: 2048

# -------------------------------------------
# Network hardware
# -------------------------------------------
esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

# Firmware update for esp32_hosted ESP32-C6
update:
  - platform: esp32_hosted
    name: ESP-Hosted Firmware
    icon: mdi:chip
    type: http
    source: https://esphome.github.io/esp-hosted-firmware/manifest/esp32c6.json
    update_interval: 6h

# -------------------------------------------
# Internal outputs
# -------------------------------------------
output:
  # Backlight LED
  - platform: ledc
    pin: GPIO23
    id: gpio_backlight_pwm
    frequency: 100Hz
    inverted: false

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    entity_category: config
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# -------------------------------------------
# Speaker Amplifier Enable
# -------------------------------------------
switch:
  - platform: gpio
    id: my_amp
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin: GPIO11
    restore_mode: RESTORE_DEFAULT_ON

# -------------------------------------------
# i2c bus
# -------------------------------------------
# Qwiic connector is also on this bus
i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

# -------------------------------------------
# Touchscreen
# -------------------------------------------
touchscreen:
  - platform: gt911
    i2c_id: bus_a
    id: my_touchscreen
    display: device_display
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: device_display
    model: JC4880P443
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 480
      height: 800

# Special LVGL settings required for this display
lvgl:
  rotation: ${rotation | default("90")}
  byte_order: little_endian

# -------------------------------------------
# Audio - speaker/mic
# -------------------------------------------
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    i2s_mclk_pin: GPIO13

audio_dac:
  - platform: es8311
    id: my_dac
    i2c_id: bus_a
    address: 0x18

audio_adc:
  - platform: es7210
    id: my_adc
    i2c_id: bus_a
    address: 0x36

microphone:
  - platform: i2s_audio
    id: my_microphone
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO48
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    id: my_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO9
    audio_dac: my_dac
    dac_type: external
    channel: mono
    buffer_duration: 500ms
    bits_per_sample: 16bit
    sample_rate: 48000

  - platform: mixer
    id: mixing_speaker
    output_speaker: my_speaker
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
